service: email-service

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: email
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
