service: email-service

provider:
  name: aws
  runtime: nodejs8.10

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: email
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
