service: email-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
          Resource: ['*']
  httpApi:
    cors: true

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - httpApi:
          path: /email
          method: POST

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
